version: '3.7'
networks:
  default:
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    networks:
      - default

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: web:5000
      #NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - web
    networks:
      - default
